name: Create Release

on:
  workflow_call:
    inputs:
      branch:
        description: The merged branch name (e.g. release/v1.1.0 or hotfix/v1.1.0)
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Extract version
        id: version
        shell: bash
        run: |
          BRANCH="${{ inputs.branch }}"
          VERSION="${BRANCH#release/}"
          VERSION="${VERSION#hotfix/}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
