name: Sync Main to Develop

on:
  workflow_call:
    inputs:
      main_branch:
        description: Main branch name
        required: false
        default: main
        type: string

      develop_branch:
        description: Develop branch name
        required: false
        default: develop
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync main into develop
        run: |
          git fetch origin

          git checkout "${{ inputs.develop_branch }}"
          git merge "origin/${{ inputs.main_branch }}" --no-edit

          git push origin "${{ inputs.develop_branch }}"
